### PR TITLE
timetable

### PR DESCRIPTION
**Pull request by aspina7**
still wip
will starting tagging ppl once have workable version with content

### CODE REVIEW

**Comment by aspina7** [comment]
@nsbatra @henryls1 @MathildeMousset 
hey folks - just pushing a suggested [timetable](https://github.com/appliedepi/emory_training/blob/c2eb36063bcfe8acde3d416878deed63a4f8c966/timetable/timetable.pdf) ... 
chucked in [author names](https://github.com/appliedepi/emory_training/pull/1/files#diff-387ab847454e2b3e2754179b8f295f2d36a58b10342a69c9b9e4dbe812ac5767R42) just to get things started but feel free to edit and push at will. 

Was going to start a [projects](https://github.com/appliedepi/emory_training/projects) page - but figured easier if we just discuss by commenting/pushing on here - and then we can add to project if we need to keep an overview. 

feelings, thoughts, tears and all other things welcome

**Comment by nsbatra** [comment]
Thanks a lot @aspina7 for drafting this. We will need to work hard to meet this very tight schedule!

I think we will need to spend a few minutes at the beginning of session 1 discussing R markdown and how it differs from R scripts.

Thankfully the last parts session 1 can be dropped if necessary (the stats and modeling case studies at least). Likewise, the GIS section of the ggplot session could be dropped if we run out of time.

**Comment by aspina7** [comment]
> very tight schedule!

agree - is going to have to go real smooth to fit in time

> session 1 discussing R markdown and how it differs from R scripts.

yep was thinking of touching on this in the session called "case study layout & R projects" - in the hopes that people had read the material? Feel like thats relatively basic stuff to know. Maybe this session should be 10 minutes then? 

> Thankfully the last parts session 1 can be dropped if necessary (the stats and modeling case studies at least). Likewise, the GIS section of the ggplot session could be dropped if we run out of time.

ye i think in terms of setting expectations this should be labelled as "nice to haves"

**Comment by aspina7** [comment]
merging for now to trial github pages

**Pull request merged**
